// Detection logic to use local server in dev and Render in production
const isLocal = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1';

// Hardcode the Render URL as the source of truth for the production environment
export const API_BASE_URL = isLocal ? '' : 'https://buildyourwolfpack-1.onrender.com'; 

export const CARD_TYPES = {
  LABOR: 'labor',
  FINANCE: 'finance',
  SALES: 'sales',
} as const;

export const GAME_BOARD: { id: number; name: string; phase: 'Measure' | 'Build' | 'Learn' }[] = [
  { id: 1, name: "Ideation", phase: "Build" },
  { id: 2, name: "Market Research", phase: "Learn" },
  { id: 3, name: "Competitive Analysis", phase: "Learn" },
  { id: 4, name: "Target Market", phase: "Measure" },
  { id: 5, name: "Unique Selling Proposition", phase: "Build" },
  { id: 6, name: "Minimum Viable Product", phase: "Build" },
  { id: 7, name: "Prototype", phase: "Build" },
  { id: 8, name: "Customer Feedback", phase: "Learn" },
  { id: 9, name: "Product/Service Refinement", phase: "Build" },
  { id: 10, name: "Branding", phase: "Build" },
  { id: 11, name: "Marketing Plan", phase: "Measure" },
  { id: 12, name: "Pricing Strategy", phase: "Measure" },
  { id: 13, name: "Launch Preparation", phase: "Build" },
  { id: 14, name: "Launch", phase: "Build" },
  { id: 15, name: "Early Sales", phase: "Measure" },
  { id: 16, name: "Customer Retention", phase: "Learn" },
  { id: 17, name: "Referral Program", phase: "Measure" },
  { id: 18, name: "Expansion", phase: "Build" },
  { id: 19, name: "Strategic Partnerships", phase: "Build" },
  { id: 20, name: "Scaling", phase: "Measure" },
  { id: 21, name: "Operations", phase: "Build" },
  { id: 22, name: "Financial Planning", phase: "Measure" },
  { id: 23, name: "Funding", phase: "Build" },
  { id: 24, name: "Investor Relations", phase: "Learn" },
  { id: 25, name: "Growth", phase: "Measure" },
  { id: 26, name: "Industry Analysis", phase: "Learn" },
  { id: 27, name: "Pivot", phase: "Learn" },
  { id: 28, name: "Innovation", phase: "Build" },
  { id: 29, name: "Intellectual Property", phase: "Build" },
  { id: 30, name: "Talent Acquisition", phase: "Build" },
  { id: 31, name: "Organizational Structure", phase: "Build" },
  { id: 32, name: "Performance Metrics", phase: "Measure" },
  { id: 33, name: "Data Analysis", phase: "Learn" },
  { id: 34, name: "Risk Management", phase: "Measure" },
  { id: 35, name: "Legal Compliance", phase: "Measure" },
  { id: 36, name: "Social Responsibility", phase: "Build" },
  { id: 37, name: "Crisis Management", phase: "Measure" },
  { id: 38, name: "Reputation Management", phase: "Learn" },
  { id: 39, name: "Exit Strategy", phase: "Measure" },
  { id: 40, name: "Success", phase: "Learn" }
];

export const PRODUCT_CARDS = [
  { id: 1, title: "Small-batch coffee blends", targetMarket: "Coffee lovers, cafes, restaurants", price: "$15 per bag", marketingChannels: "Social media ads, farmers markets" },
  { id: 2, title: "Customized meal prep kits", targetMarket: "Health-conscious individuals, busy professionals", price: "$10 per serving", marketingChannels: "Online ads, word-of-mouth" },
  { id: 3, title: "Handmade natural soaps", targetMarket: "Eco-conscious consumers, gift shops, boutiques", price: "$8 per bar", marketingChannels: "Local craft fairs, social media" },
  { id: 4, title: "Personalized tutoring services", targetMarket: "Students, parents, schools", price: "$30 per hour", marketingChannels: "Referrals, school partnerships" },
  { id: 5, title: "On-demand lawn mowing and maintenance", targetMarket: "Homeowners, property management companies", price: "$50 per hour", marketingChannels: "Local SEO, yard signs" },
  { id: 6, title: "Subscription-based book box service", targetMarket: "Book lovers, gift-givers", price: "$20 per month", marketingChannels: "Social media, book clubs" },
  { id: 7, title: "Online language classes", targetMarket: "Language learners, international students", price: "$15 per hour", marketingChannels: "SEO, online ads" },
  { id: 8, title: "Handmade jewelry", targetMarket: "Fashion-conscious individuals, gift shops, boutiques", price: "$25 per piece", marketingChannels: "Social media, local markets" },
  { id: 9, title: "Virtual interior design services", targetMarket: "Homeowners, real estate agents", price: "$200 per room", marketingChannels: "Instagram, referral partnerships" },
  { id: 10, title: "Mobile car detailing", targetMarket: "Car owners, car dealerships", price: "$150 per job", marketingChannels: "Facebook ads, referrals" },
  { id: 11, title: "Homemade pet treats", targetMarket: "Pet owners, pet stores, farmers markets", price: "$5 per bag", marketingChannels: "Local events, social media" },
  { id: 12, title: "Personalized workout plans", targetMarket: "Fitness enthusiasts, personal trainers", price: "$50 per plan", marketingChannels: "Referrals, social media" },
  { id: 13, title: "Customized meal delivery service", targetMarket: "Health-conscious individuals, busy professionals", price: "$12 per meal", marketingChannels: "Online ads, word-of-mouth" },
  { id: 14, title: "Mobile bike repair services", targetMarket: "Cyclists, bike shops", price: "$60 per hour", marketingChannels: "Facebook ads, referral partnerships" },
  { id: 15, title: "Handmade candles", targetMarket: "Home decor enthusiasts, gift shops, boutiques", price: "$15 per candle", marketingChannels: "Local craft fairs, social media" },
  { id: 16, title: "Social media management services", targetMarket: "Small businesses, entrepreneurs", price: "$300 per month", marketingChannels: "SEO, referrals" },
  { id: 17, title: "Event planning services", targetMarket: "Event hosts, businesses", price: "$500 per event", marketingChannels: "Word-of-mouth, vendor partnerships" },
  { id: 18, title: "Online personal shopping services", targetMarket: "Busy professionals, fashion-conscious individuals", price: "$50 per hour", marketingChannels: "Instagram, referral partnerships" },
  { id: 19, title: "Eco-friendly cleaning services", targetMarket: "Homeowners, property management companies", price: "$80 per hour", marketingChannels: "Facebook ads, referral partnerships" },
  { id: 20, title: "Home repair and maintenance services", targetMarket: "Homeowners, property management companies", price: "$50 per hour", marketingChannels: "SEO, yard signs" },
  { id: 21, title: "Customized gift baskets", targetMarket: "Gift-givers, businesses", price: "$50 per basket", marketingChannels: "Social media, referral partnerships" },
  { id: 22, title: "Mobile car wash services", targetMarket: "Car owners, car dealerships", price: "$50 per wash", marketingChannels: "Facebook ads, referrals" },
  { id: 23, title: "Virtual bookkeeping services", targetMarket: "Small businesses, entrepreneurs", price: "$100 per month", marketingChannels: "Referral partnerships, SEO" },
  { id: 24, title: "Handmade pottery", targetMarket: "Home decor enthusiasts, gift shops, boutiques", price: "$30 per piece", marketingChannels: "Local craft fairs, social media" },
  { id: 25, title: "Personalized skincare routines", targetMarket: "Beauty enthusiasts, aestheticians", price: "$50 per routine", marketingChannels: "Social media, referral partnerships" },
  { id: 26, title: "Healthy vending machines", targetMarket: "Health-conscious individuals, gyms, schools", price: "$2-$5 per item", marketingChannels: "SEO, location partnerships" },
  { id: 27, title: "Online fitness classes", targetMarket: "Fitness enthusiasts, busy professionals", price: "$20 per month", marketingChannels: "Social media ads, influencer partnerships" },
  { id: 28, title: "Personal Styling Service", targetMarket: "Busy professionals", price: "$75/hour", marketingChannels: "Social media advertising, referral programs" },
  { id: 29, title: "Online Coaching Services", targetMarket: "Students and young professionals", price: "$50/session", marketingChannels: "Influencer marketing, email marketing" },
  { id: 30, title: "Home Cleaning Services", targetMarket: "Homeowners and renters", price: "$100/visit", marketingChannels: "Local flyers, word-of-mouth referrals" },
  { id: 31, title: "Pet-Sitting Services", targetMarket: "Pet owners", price: "$20/day", marketingChannels: "Local pet stores, veterinarian referrals" },
  { id: 32, title: "Food Delivery Services", targetMarket: "Busy professionals and families", price: "$10/delivery + cost of food", marketingChannels: "Social media advertising, referral programs" },
  { id: 33, title: "Social Media Management Services", targetMarket: "Small business owners", price: "$500/month", marketingChannels: "Email marketing, LinkedIn outreach" },
  { id: 34, title: "Event Planning Services", targetMarket: "Wedding and party planners", price: "$100/hour", marketingChannels: "Wedding expo booths, vendor referrals" },
  { id: 35, title: "Online Fitness Coaching", targetMarket: "Fitness enthusiasts", price: "$75/month", marketingChannels: "Instagram influencer marketing, referral programs" },
  { id: 36, title: "Graphic Design Services", targetMarket: "Small business owners", price: "$50/hour", marketingChannels: "LinkedIn outreach, referral programs" },
  { id: 37, title: "Lawn Care Services", targetMarket: "Homeowners", price: "$50/visit", marketingChannels: "Local flyers, word-of-mouth referrals" },
  { id: 38, title: "Language Translation Services", targetMarket: "International businesses", price: "$0.10/word", marketingChannels: "LinkedIn outreach, email marketing" },
  { id: 39, title: "Language Translation Services", targetMarket: "International businesses", price: "$0.10/word", marketingChannels: "LinkedIn outreach, email marketing" },
  { id: 40, title: "Online Tutoring Services", targetMarket: "Students and parents", price: "$30/session", marketingChannels: "School referrals, word-of-mouth referrals" },
  { id: 41, title: "Car Detailing Services", targetMarket: "Car owners", price: "$150/visit", marketingChannels: "Local flyers, word-of-mouth referrals" },
  { id: 42, title: "Virtual Interior Design Services", targetMarket: "Homeowners and renters", price: "$500/room", marketingChannels: "Social media advertising, referral programs" },
  { id: 43, title: "Personal Concierge Services", targetMarket: "High-income individuals", price: "$75/hour", marketingChannels: "LinkedIn outreach, referral programs" },
  { id: 44, title: "Mobile Car Wash Services", targetMarket: "Car owners", price: "$25/wash", marketingChannels: "Local flyers, word-of-mouth referrals" },
  { id: 45, title: "Content Writing Services", targetMarket: "Small business owners", price: "$0.10/word", marketingChannels: "LinkedIn outreach, email marketing" },
  { id: 46, title: "Personal Shopping Services", targetMarket: "Busy professionals and high-income individuals", price: "$75/hour", marketingChannels: "Instagram influencer marketing, referral programs" },
  { id: 47, title: "IT Consulting Services", targetMarket: "Small business owners", price: "$75/hour", marketingChannels: "LinkedIn outreach, email marketing" },
  { id: 48, title: "Online Course Creation Services", targetMarket: "Educators and subject matter experts", price: "$1000/course", marketingChannels: "Email marketing, influencer marketing" },
  { id: 49, title: "Social Media Advertising Services", targetMarket: "Small business owners", price: "$1000/month", marketingChannels: "LinkedIn outreach, email marketing" },
  { id: 50, title: "House Sitting Services", targetMarket: "Homeowners", price: "$50/day", marketingChannels: "Local flyers, word-of-mouth referrals" },
  { id: 51, title: "Virtual Bookkeeping Services", targetMarket: "Small business owners", price: "$500/month", marketingChannels: "LinkedIn outreach, email marketing" },
  { id: 52, title: "Resume Writing Services", targetMarket: "Job seekers", price: "$100/resume", marketingChannels: "LinkedIn outreach, referral programs" }
];
